/* PQ/T Hybrid Suite C ABI — auto-generated by cbindgen. Do not edit. */
/*
 * No aliasing (caller obligation): within a single call, input (ptr,len) buffers and
 * output (ptr,len) buffers MUST NOT overlap. Each call reads its inputs and writes its
 * outputs concurrently; overlapping regions are undefined behavior. Pass distinct buffers.
 */

#ifndef Q_PERIAPT_H
#define Q_PERIAPT_H

#pragma once

/* Generated; regenerate with: cbindgen --config cbindgen.toml --crate q-periapt-ffi --output include/q_periapt.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define Q_PERIAPT_OK 0

/**
 * A required pointer was null.
 */
#define Q_PERIAPT_ERR_NULL -1

/**
 * A buffer had the wrong length.
 */
#define Q_PERIAPT_ERR_LENGTH -2

/**
 * The requested algorithm/profile combination is forbidden by policy.
 */
#define Q_PERIAPT_ERR_POLICY -3

/**
 * A panic was caught at the ABI boundary.
 */
#define Q_PERIAPT_ERR_PANIC -4

/**
 * An internal/backend error.
 */
#define Q_PERIAPT_ERR_INTERNAL -5

/**
 * `profile = 1`: fast X-Wing-compatible combiner.
 */
#define Q_PERIAPT_PROFILE_COMPAT_XWING 1

/**
 * `profile = 2`: context-bound combiner.
 */
#define Q_PERIAPT_PROFILE_CONTEXT_BOUND 2

/**
 * ML-KEM-768 secret-key length, bytes.
 */
#define Q_PERIAPT_MLKEM768_SK_LEN 2400

/**
 * ML-KEM-768 public-key length, bytes.
 */
#define Q_PERIAPT_MLKEM768_PK_LEN 1184

/**
 * ML-KEM-768 ciphertext length, bytes.
 */
#define Q_PERIAPT_MLKEM768_CT_LEN 1088

/**
 * X25519 key / ciphertext length, bytes.
 */
#define Q_PERIAPT_X25519_LEN 32

/**
 * Combined shared-secret length, bytes.
 */
#define Q_PERIAPT_SECRET_LEN 32

/**
 * Verify a detached-signed agility policy (`toml` + `signature`) under `vk` with the suite's
 * ML-DSA-65 root verifier, and write the combiner profile code its `select_profile()` chooses
 * into `out_profile` (one byte: [`Q_PERIAPT_PROFILE_COMPAT_XWING`] or
 * [`Q_PERIAPT_PROFILE_CONTEXT_BOUND`]). This threads the policy engine into the C ABI: load a
 * signed policy once, then pass the returned code to encapsulate/decapsulate instead of
 * hard-coding a profile. **Fail-closed:** an unauthenticated, weak-signer, or rolled-back policy
 * yields [`Q_PERIAPT_ERR_POLICY`]. Rollback is enforced against `last_trusted_version`: a
 * validly-signed policy whose `policy_version` is *older* than that is refused (pass `0` to accept
 * any version on first load; persist the accepted `policy_version` and pass it back thereafter).
 *
 * # Safety
 * `toml`/`signature`/`vk` must be readable for their lengths; `out_profile` writable for
 * `out_profile_len` (which must be `1`). Input and output buffers must not overlap (see the
 * module-level no-aliasing convention).
 */
int32_t q_periapt_profile_from_signed_policy(const uint8_t *toml,
                                             uintptr_t toml_len,
                                             const uint8_t *signature,
                                             uintptr_t signature_len,
                                             const uint8_t *vk,
                                             uintptr_t vk_len,
                                             uint32_t last_trusted_version,
                                             uint8_t *out_profile,
                                             uintptr_t out_profile_len);

/**
 * Deterministically derive an ML-KEM-768 key pair from a 64-byte `seed`.
 *
 * # Safety
 * `seed`/`out_sk`/`out_pk` must point to readable/writable regions of the given
 * lengths (`64` / [`Q_PERIAPT_MLKEM768_SK_LEN`] / [`Q_PERIAPT_MLKEM768_PK_LEN`]).
 */
int32_t q_periapt_mlkem768_keypair(const uint8_t *seed,
                                   uintptr_t seed_len,
                                   uint8_t *out_sk,
                                   uintptr_t out_sk_len,
                                   uint8_t *out_pk,
                                   uintptr_t out_pk_len);

/**
 * Deterministically derive an X25519 key pair from a 32-byte scalar.
 *
 * # Safety
 * All pointers must be valid for the given lengths (`32` each).
 */
int32_t q_periapt_x25519_keypair(const uint8_t *secret,
                                 uintptr_t secret_len,
                                 uint8_t *out_sk,
                                 uintptr_t out_sk_len,
                                 uint8_t *out_pk,
                                 uintptr_t out_pk_len);

/**
 * Hybrid encapsulation to `(pk_pq, pk_trad)`.
 *
 * Writes `out_ct_pq` ([`Q_PERIAPT_MLKEM768_CT_LEN`]), `out_ct_trad` ([`Q_PERIAPT_X25519_LEN`])
 * and `out_secret` ([`Q_PERIAPT_SECRET_LEN`]). `context` is bound only under
 * [`Q_PERIAPT_PROFILE_CONTEXT_BOUND`] and must then be non-empty.
 *
 * # Safety
 * Every `(ptr, len)` pair must describe a valid region; output buffers must be
 * writable for their lengths.
 */
int32_t q_periapt_hybrid_encapsulate(uint8_t profile,
                                     const uint8_t *suite_id,
                                     uintptr_t suite_id_len,
                                     uint32_t policy_version,
                                     const uint8_t *pk_pq,
                                     uintptr_t pk_pq_len,
                                     const uint8_t *pk_trad,
                                     uintptr_t pk_trad_len,
                                     const uint8_t *context,
                                     uintptr_t context_len,
                                     const uint8_t *rand_pq,
                                     uintptr_t rand_pq_len,
                                     const uint8_t *rand_trad,
                                     uintptr_t rand_trad_len,
                                     uint8_t *out_ct_pq,
                                     uintptr_t out_ct_pq_len,
                                     uint8_t *out_ct_trad,
                                     uintptr_t out_ct_trad_len,
                                     uint8_t *out_secret,
                                     uintptr_t out_secret_len);

/**
 * Hybrid decapsulation. Returns [`Q_PERIAPT_OK`] and writes `out_secret`
 * ([`Q_PERIAPT_SECRET_LEN`]) for any correctly-sized ciphertext; an invalid ciphertext
 * yields a pseudorandom secret (implicit rejection — no oracle).
 *
 * # Safety
 * Every `(ptr, len)` pair must describe a valid region; `out_secret` must be
 * writable for [`Q_PERIAPT_SECRET_LEN`].
 */
int32_t q_periapt_hybrid_decapsulate(uint8_t profile,
                                     const uint8_t *suite_id,
                                     uintptr_t suite_id_len,
                                     uint32_t policy_version,
                                     const uint8_t *sk_pq,
                                     uintptr_t sk_pq_len,
                                     const uint8_t *ct_pq,
                                     uintptr_t ct_pq_len,
                                     const uint8_t *pk_pq,
                                     uintptr_t pk_pq_len,
                                     const uint8_t *sk_trad,
                                     uintptr_t sk_trad_len,
                                     const uint8_t *ct_trad,
                                     uintptr_t ct_trad_len,
                                     const uint8_t *pk_trad,
                                     uintptr_t pk_trad_len,
                                     const uint8_t *context,
                                     uintptr_t context_len,
                                     uint8_t *out_secret,
                                     uintptr_t out_secret_len);

/**
 * Derive a combined secret directly from the combiner inputs — exposes the
 * `combine()` core (not the full hybrid) so the `ContextBound` / `CompatXWing`
 * reference vectors are reproducible byte-for-byte across every binding face.
 *
 * `input` is the nine combiner fields, each 8-byte big-endian length-prefixed, in
 * the canonical order: `suite_id`, `policy_version` (a 4-byte big-endian `u32`),
 * `ss_pq`, `ss_trad`, `ct_pq`, `pk_pq`, `ct_trad`, `pk_trad`, `context`. `profile`
 * is [`Q_PERIAPT_PROFILE_COMPAT_XWING`] or [`Q_PERIAPT_PROFILE_CONTEXT_BOUND`].
 *
 * # Safety
 * `input`/`out_secret` must be valid for `input_len` / [`Q_PERIAPT_SECRET_LEN`].
 */
int32_t q_periapt_combine(uint8_t profile,
                          const uint8_t *input,
                          uintptr_t input_len,
                          uint8_t *out_secret,
                          uintptr_t out_secret_len);

#endif  /* Q_PERIAPT_H */
