/* PQ/T Hybrid Suite C ABI — auto-generated by cbindgen. Do not edit. */
/*
 * No aliasing (checked): within a single call, input (ptr,len) buffers and output (ptr,len)
 * buffers must not overlap (concurrent read/write of the same memory is undefined behavior).
 * The multi-buffer entry points CHECK the ranges and return Q_PERIAPT_ERR_ALIASING (-7) before
 * any access, so an overlap is a defined error, not UB. Pass distinct buffers regardless.
 */

#ifndef Q_PERIAPT_ABI2_H
#define Q_PERIAPT_ABI2_H

#pragma once

/* Generated; regenerate with: cbindgen --config cbindgen.toml --crate q-periapt-ffi --output include/q_periapt.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C ABI version for this header/library contract.
 */
#define Q_PERIAPT_ABI_VERSION 2

/**
 * Maximum exact signed-policy document size accepted by the policy ABI.
 */
#define Q_PERIAPT_MAX_SIGNED_POLICY_BYTES 65536

/**
 * Maximum application-context size accepted by policy-bound operations.
 */
#define Q_PERIAPT_MAX_APPLICATION_CONTEXT_BYTES 65536

/**
 * Success.
 */
#define Q_PERIAPT_OK 0

/**
 * A required pointer was null.
 */
#define Q_PERIAPT_ERR_NULL -1

/**
 * A buffer had the wrong length.
 */
#define Q_PERIAPT_ERR_LENGTH -2

/**
 * The requested algorithm/profile combination is forbidden by policy.
 */
#define Q_PERIAPT_ERR_POLICY -3

/**
 * A panic was caught at the ABI boundary.
 */
#define Q_PERIAPT_ERR_PANIC -4

/**
 * An internal/backend error.
 */
#define Q_PERIAPT_ERR_INTERNAL -5

/**
 * A supplied **public** key share was invalid (e.g. a low-order / non-contributory X25519 share,
 * which would force an all-zero DH secret). This is a public-input validity rejection — it depends
 * only on attacker-known inputs, **not** on the secret key, so it is not a decapsulation oracle.
 */
#define Q_PERIAPT_ERR_INVALID_KEYSHARE -6

/**
 * An output buffer overlapped an input (or another output) buffer. Rather than risk the undefined
 * behavior of materializing aliasing `&[u8]`/`&mut [u8]`, the call is rejected. (Callers should pass
 * disjoint buffers; their required lengths differ in any case.)
 */
#define Q_PERIAPT_ERR_ALIASING -7

/**
 * The operating-system cryptographic random-number generator failed.
 */
#define Q_PERIAPT_ERR_ENTROPY -8

/**
 * `profile = 2`: context-bound combiner.
 */
#define Q_PERIAPT_PROFILE_CONTEXT_BOUND 2

/**
 * Canonical signed-policy decision encoding version.
 */
#define Q_PERIAPT_POLICY_DECISION_VERSION 1

/**
 * Length of a trusted policy state (`version_be || SHA3-256(exact_policy_bytes)`).
 */
#define Q_PERIAPT_TRUSTED_POLICY_STATE_LEN 36

/**
 * Length of an authenticated fixed-suite decision.
 *
 * Layout: `decision_version || suite_code || profile_code || key_format_code ||
 * policy_version_be || policy_digest`.
 */
#define Q_PERIAPT_POLICY_DECISION_LEN 40

/**
 * Suite code for the fixed ML-KEM-768 + X25519 ABI.
 */
#define Q_PERIAPT_SUITE_MLKEM768_X25519 1

/**
 * Expanded/importable secret-key representation.
 */
#define Q_PERIAPT_KEY_FORMAT_EXPANDED 1

/**
 * ML-KEM-768 secret-key length, bytes.
 */
#define Q_PERIAPT_MLKEM768_SK_LEN 2400

/**
 * ML-KEM-768 public-key length, bytes.
 */
#define Q_PERIAPT_MLKEM768_PK_LEN 1184

/**
 * ML-KEM-768 ciphertext length, bytes.
 */
#define Q_PERIAPT_MLKEM768_CT_LEN 1088

/**
 * X25519 key / ciphertext length, bytes.
 */
#define Q_PERIAPT_X25519_LEN 32

/**
 * Combined shared-secret length, bytes.
 */
#define Q_PERIAPT_SECRET_LEN 32

/**
 * Return the C ABI version implemented by this library. Consumers should compare this against
 * [`Q_PERIAPT_ABI_VERSION`] at startup before trusting any length constants or entry points.
 */
uint32_t q_periapt_abi_version(void);

/**
 * Return the crate version string for the linked native library.
 */
const char *q_periapt_version(void);

/**
 * Return the fixed suite id implemented by this C ABI as a NUL-terminated ASCII string.
 */
const char *q_periapt_fixed_suite_id(void);

/**
 * Return the fixed suite id length, excluding the terminating NUL.
 */
uintptr_t q_periapt_fixed_suite_id_len(void);

/**
 * Return a stable ASCII name for a status code. Unknown status codes return `UNKNOWN_STATUS`.
 */
const char *q_periapt_status_name(int32_t code);

/**
 * Verify a detached, domain-separated signed agility policy and atomically resolve it against
 * the only suite implemented by this ABI (ML-KEM-768 + X25519).
 *
 * On success `out_decision` receives [`Q_PERIAPT_POLICY_DECISION_LEN`] canonical bytes containing
 * the selected suite, profile, key format, non-zero policy version, and SHA3-256 identity of the
 * exact signed policy. A policy that requires L5/ML-KEM-1024 is rejected instead of silently
 * executing this L3 fixed suite. Persist bytes 4..40 as the next `last_trusted_state`; pass an
 * empty state only for an explicitly provisioned first load. A lower version or different policy
 * reusing the same version is rejected. The verification key is a trust root and therefore must
 * be pinned by the host; accepting it from the same untrusted channel as the policy permits an
 * attacker to self-sign a replacement policy. **Fail-closed:** after the caller supplies a valid,
 * disjoint, exact-length output, every subsequent length/authentication/parse/resolve error leaves
 * that output all-zero. Earlier public output-contract or aliasing errors return without writing an
 * output whose extent or disjointness is invalid. A legacy ABI 1 four-byte version is rejected:
 * it cannot be upgraded without the exact previously accepted policy bytes and must go through an
 * explicit host-authorized re-enrollment/reset flow.
 *
 * # Safety
 * `toml`/`signature`/`vk`/`last_trusted_state` must be readable for their lengths;
 * `out_decision` writable for `out_decision_len`, which must equal
 * [`Q_PERIAPT_POLICY_DECISION_LEN`]. `last_trusted_state_len` must be zero or
 * [`Q_PERIAPT_TRUSTED_POLICY_STATE_LEN`]. Inputs and output must not overlap.
 */
int32_t q_periapt_decision_from_signed_policy(const uint8_t *toml,
                                              uintptr_t toml_len,
                                              const uint8_t *signature,
                                              uintptr_t signature_len,
                                              const uint8_t *vk,
                                              uintptr_t vk_len,
                                              const uint8_t *last_trusted_state,
                                              uintptr_t last_trusted_state_len,
                                              uint8_t *out_decision,
                                              uintptr_t out_decision_len);

/**
 * Generate the fixed-suite ML-KEM-768 and X25519 key pairs from the operating
 * system CSPRNG under one authenticated policy decision.
 *
 * The decision must select the context-bound/expanded-key product profile. No
 * deterministic seed is accepted by the product ABI; deterministic derivation
 * remains an internal KAT facility so production callers cannot accidentally
 * reuse low-entropy test material.
 *
 * The encoded decision is an integrity-preserving value between trusted
 * components in one process, not an unforgeable capability. The host must pin
 * the verification key used to create it and isolate untrusted native code.
 *
 * # Safety
 * `decision` must be readable for `decision_len`. All four outputs must be
 * writable for their exact published lengths and disjoint from the input and
 * from one another.
 */
int32_t q_periapt_generate_keypair(const uint8_t *decision,
                                   uintptr_t decision_len,
                                   uint8_t *out_sk_pq,
                                   uintptr_t out_sk_pq_len,
                                   uint8_t *out_pk_pq,
                                   uintptr_t out_pk_pq_len,
                                   uint8_t *out_sk_trad,
                                   uintptr_t out_sk_trad_len,
                                   uint8_t *out_pk_trad,
                                   uintptr_t out_pk_trad_len);

/**
 * Hybrid encapsulation authorized by an authenticated policy decision.
 *
 * This is the only product encapsulation entry point. It derives suite/profile/version from one
 * canonical decision and injectively wraps `application_context` together with the exact signed
 * policy digest before invoking the context-bound combiner. `CompatXWing` decisions are rejected
 * because that profile intentionally ignores context and therefore cannot commit the digest.
 * Encapsulation coins come from the operating-system CSPRNG; deterministic coins are not exposed
 * by the product ABI.
 *
 * The decision is an integrity-preserving high-level API between trusted components of one
 * process; C memory is caller-writable, so hostile native code in the same process can still forge
 * it or bypass this entry point. Use process isolation when local native callers are untrusted.
 *
 * # Safety
 * Every `(ptr, len)` pair must describe a valid region. Outputs must be writable and disjoint
 * from every input and from each other.
 */
int32_t q_periapt_encapsulate(const uint8_t *decision,
                              uintptr_t decision_len,
                              const uint8_t *pk_pq,
                              uintptr_t pk_pq_len,
                              const uint8_t *pk_trad,
                              uintptr_t pk_trad_len,
                              const uint8_t *application_context,
                              uintptr_t application_context_len,
                              uint8_t *out_ct_pq,
                              uintptr_t out_ct_pq_len,
                              uint8_t *out_ct_trad,
                              uintptr_t out_ct_trad_len,
                              uint8_t *out_secret,
                              uintptr_t out_secret_len);

/**
 * Hybrid decapsulation authorized by an authenticated policy decision.
 *
 * Suite/profile/version and the policy-bound context are reconstructed exactly as in
 * [`q_periapt_encapsulate`]. See that function for the same-process trust
 * boundary and `CompatXWing` rejection rationale.
 *
 * # Safety
 * Every `(ptr, len)` pair must describe a valid region. `out_secret` must be writable and
 * disjoint from every input.
 */
int32_t q_periapt_decapsulate(const uint8_t *decision,
                              uintptr_t decision_len,
                              const uint8_t *sk_pq,
                              uintptr_t sk_pq_len,
                              const uint8_t *ct_pq,
                              uintptr_t ct_pq_len,
                              const uint8_t *pk_pq,
                              uintptr_t pk_pq_len,
                              const uint8_t *sk_trad,
                              uintptr_t sk_trad_len,
                              const uint8_t *ct_trad,
                              uintptr_t ct_trad_len,
                              const uint8_t *pk_trad,
                              uintptr_t pk_trad_len,
                              const uint8_t *application_context,
                              uintptr_t application_context_len,
                              uint8_t *out_secret,
                              uintptr_t out_secret_len);

#endif  /* Q_PERIAPT_ABI2_H */
