"""Reproduce the public C SDK transition fixture from the shared JSON vectors.

Generate JSON with gen_signed_policy_vector -- 3 --disable-suite and -- 4.
Default checks the checked-in header; --write explicitly regenerates it.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from evidence_io import load_json_object_snapshot

ROOT = Path(__file__).resolve().parent.parent


def render() -> str:
    original = load_json_object_snapshot(ROOT / "bindings/signed-policy-vectors.json", label="initial policy fixture").value
    parts = [
        "/* Generated by artifact/sdk_policy_fixtures.py; public test material only. */",
        "#ifndef Q_PERIAPT_SDK_POLICY_UPDATE_FIXTURE_H",
        "#define Q_PERIAPT_SDK_POLICY_UPDATE_FIXTURE_H",
        "#include <stdint.h>",
    ]
    for name, version, prefix in (("revocation", 3, "QP_REVOKED"), ("update", 4, "QP_UPDATED")):
        doc = load_json_object_snapshot(ROOT / f"bindings/sdk-policy-{name}-vectors.json", label=f"{name} policy fixture").value
        if doc["verification_key"] != original["verification_key"] or doc["policy_version"] != version:
            raise ValueError("SDK policy fixture root/version mismatch")
        values = {"POLICY": doc["policy_toml"].encode(), "SIGNATURE": bytes.fromhex(doc["signature"]),
                  "STATE": version.to_bytes(4, "big") + bytes.fromhex(doc["policy_digest"])}
        if len(values["SIGNATURE"]) != 3309 or len(values["STATE"]) != 36:
            raise ValueError("SDK fixture signature/state shape mismatch")
        for field, data in values.items():
            parts.append(f"static const uint8_t {prefix}_{field}[] = {{")
            parts.extend("    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 16]) + ","
                         for i in range(0, len(data), 16))
            parts.append("};")
    parts.extend(("#endif", ""))
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    path = ROOT / "bindings/c/sdk_policy_update_fixture.h"
    expected = render()
    if args.write:
        path.write_text(expected)
    elif path.read_text() != expected:
        raise ValueError("stale C SDK policy fixture")
    print("SDK_POLICY_FIXTURES_PASS")


if __name__ == "__main__":
    main()
