"""Structural npm acceptance controls; cryptography runs in real installed WASM."""
from pathlib import Path
import copy
import json
import tempfile
import unittest

import third_party_licenses as licenses
import wasm_sdk_package as wasm


class WasmSDKPackageTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        for relative in wasm.entries(wasm.CRATE / "package"):
            wasm.copy(wasm.CRATE / "package" / relative, self.root / relative)
        wasm.copy(wasm.CRATE / "PackageREADME.md", self.root / "README.md")
        for name in wasm.NOTICES:
            wasm.copy(wasm.ROOT / name, self.root / name)
        for name in wasm.VENDOR_NOTICES:
            wasm.copy(wasm.ROOT / "crates/q-periapt-mlkem-native-sys/vendor" / name,
                      self.root / "LICENSES/mlkem-native" / name)
        for environment in ("node", "web"):
            for name in wasm.GENERATED:
                (self.root / environment / name).write_bytes(b"fixture generated bytes")
        license_path = self.root / "THIRD_PARTY/rust/example-1.0.0/LICENSE"
        license_path.parent.mkdir(parents=True)
        license_path.write_text("fixture license\n")
        data = wasm.snapshot(license_path)
        inventory = {"schema_version": licenses.SCHEMA_VERSION, "kind": licenses.KIND,
            "root_package": wasm.NAME, "target": wasm.TARGET, "packages": [{
                "name": "example", "version": "1.0.0", "source": "registry+https://github.com/rust-lang/crates.io-index",
                "checksum": "a" * 64, "license_expression": "MIT", "license_files": [{
                    "path": "THIRD_PARTY/rust/example-1.0.0/LICENSE", "bytes": data.size, "sha256": data.sha256}]}]}
        (self.root / licenses.INVENTORY_RELATIVE).write_bytes(licenses.canonical_json(inventory))
        self.seal()

    def seal(self):
        contents = self.root / wasm.CONTENTS
        if contents.exists():
            contents.unlink()  # Owned temporary unit fixture only.
        wasm.write_json(contents, {"schema_version": 1, "name": wasm.NAME, "version": wasm.VERSION,
            "release_claim_eligible": False, "sources": {}, "tools": {}, "files": wasm.entries(self.root)})
        self.sha = wasm.snapshot(contents).sha256

    def test_pinned_manifest_and_generated_payload_mutation(self):
        self.assertEqual(wasm.verify(self.root, self.sha)["version"], wasm.VERSION)
        with self.assertRaisesRegex(ValueError, "pinned manifest"):
            wasm.verify(self.root, "0" * 64)
        (self.root / "web/q_periapt_sdk_wasm_bg.wasm").write_bytes(b"altered wasm")
        with self.assertRaisesRegex(ValueError, "inventory or digest"):
            wasm.verify(self.root, self.sha)

    def test_rehashed_default_expert_exposure_is_rejected(self):
        path = self.root / "index.cjs"
        path.write_text(path.read_text() + "\nexports.QPeriaptExpert = sdk.QPeriaptExpert;\n")
        self.seal()
        with self.assertRaisesRegex(ValueError, "public entry differs"):
            wasm.verify(self.root, self.sha)

    def test_rehashed_missing_generated_file_and_notice_are_rejected(self):
        (self.root / "web/q_periapt_sdk_wasm.d.ts").unlink()
        self.seal()
        with self.assertRaisesRegex(ValueError, "generated payload is incomplete"):
            wasm.verify(self.root, self.sha)
        (self.root / "web/q_periapt_sdk_wasm.d.ts").write_bytes(b"fixture generated bytes")
        (self.root / "LICENSES/Rust-1.98.1-library.html").unlink()
        self.seal()
        with self.assertRaisesRegex(ValueError, "notice or README"):
            wasm.verify(self.root, self.sha)

    def test_extra_file_and_symlink_are_rejected(self):
        path = self.root / "unexpected.js"
        path.write_text("unexpected")
        with self.assertRaisesRegex(ValueError, "inventory or digest"):
            wasm.verify(self.root, self.sha)
        path.unlink()
        path.symlink_to(self.root / "index.cjs")
        with self.assertRaisesRegex(ValueError, "symlink"):
            wasm.verify(self.root, self.sha)

    def test_schema_requires_integer_version(self):
        path = self.root / wasm.CONTENTS
        original = json.loads(path.read_text())
        for value in (True, 1.0, "1"):
            with self.subTest(value=value):
                changed = copy.deepcopy(original)
                changed["schema_version"] = value
                path.write_text(json.dumps(changed))
                with self.assertRaisesRegex(ValueError, "manifest schema"):
                    wasm.verify(self.root, wasm.snapshot(path).sha256)

    def test_minimum_runtime_is_exact_and_archive_must_match_consumer_source(self):
        wasm.validate_node_version("v24.0.0", "v24.0.0")
        wasm.validate_node_version("v26.3.0", None)
        for actual in ("v23.11.0", "v24.1.0", "24.0.0", "v24.0.0-pre"):
            with self.subTest(actual=actual), self.assertRaises(ValueError):
                wasm.validate_node_version(actual, "v24.0.0")
        current = wasm.sources()
        wasm.validate_consumer_source({"sources": current})
        changed = copy.deepcopy(current)
        changed["rust_workspace_sha256"] = "0" * 64
        with self.assertRaisesRegex(ValueError, "archive source differs"):
            wasm.validate_consumer_source({"sources": changed})

    def test_ci_consumes_the_produced_archive_on_exact_minimum_runtime(self):
        from test_proof_to_byte_release import extract_workflow_job
        workflow = (wasm.ROOT / ".github/workflows/ci.yml").read_text()
        job = extract_workflow_job(workflow, "bindings-wasm")
        build = job.index("Build and install product WASM package outside the checkout")
        minimum = job.index('node-version: "24.0.0"')
        consume = job.index("Consume the same WASM archive on Node 24.0.0")
        self.assertLess(build, minimum)
        self.assertLess(minimum, consume)
        for token in ("--archive-sha256", "--manifest-sha256", "--node", "--npm-cli",
                      "--expected-node-version v24.0.0", "target/sdk-wasm-node24-minimum/*.json"):
            self.assertIn(token, job)
        self.assertNotIn("continue-on-error:", job)


if __name__ == "__main__":
    unittest.main()
