/* PQ/T Hybrid Suite C ABI — auto-generated by cbindgen. Do not edit. */

#ifndef PQT_H
#define PQT_H

#pragma once

/* Generated; regenerate with: cbindgen --config cbindgen.toml --crate pqt-ffi --output include/pqt.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define PQT_OK 0

/**
 * A required pointer was null.
 */
#define PQT_ERR_NULL -1

/**
 * A buffer had the wrong length.
 */
#define PQT_ERR_LENGTH -2

/**
 * The requested algorithm/profile combination is forbidden by policy.
 */
#define PQT_ERR_POLICY -3

/**
 * A panic was caught at the ABI boundary.
 */
#define PQT_ERR_PANIC -4

/**
 * An internal/backend error.
 */
#define PQT_ERR_INTERNAL -5

/**
 * `profile = 1`: fast X-Wing-compatible combiner.
 */
#define PQT_PROFILE_COMPAT_XWING 1

/**
 * `profile = 2`: context-bound combiner.
 */
#define PQT_PROFILE_CONTEXT_BOUND 2

/**
 * ML-KEM-768 secret-key length, bytes.
 */
#define PQT_MLKEM768_SK_LEN 2400

/**
 * ML-KEM-768 public-key length, bytes.
 */
#define PQT_MLKEM768_PK_LEN 1184

/**
 * ML-KEM-768 ciphertext length, bytes.
 */
#define PQT_MLKEM768_CT_LEN 1088

/**
 * X25519 key / ciphertext length, bytes.
 */
#define PQT_X25519_LEN 32

/**
 * Combined shared-secret length, bytes.
 */
#define PQT_SECRET_LEN 32

/**
 * Deterministically derive an ML-KEM-768 key pair from a 64-byte `seed`.
 *
 * # Safety
 * `seed`/`out_sk`/`out_pk` must point to readable/writable regions of the given
 * lengths (`64` / [`PQT_MLKEM768_SK_LEN`] / [`PQT_MLKEM768_PK_LEN`]).
 */
int32_t pqt_mlkem768_keypair(const uint8_t *seed,
                             uintptr_t seed_len,
                             uint8_t *out_sk,
                             uintptr_t out_sk_len,
                             uint8_t *out_pk,
                             uintptr_t out_pk_len);

/**
 * Deterministically derive an X25519 key pair from a 32-byte scalar.
 *
 * # Safety
 * All pointers must be valid for the given lengths (`32` each).
 */
int32_t pqt_x25519_keypair(const uint8_t *secret,
                           uintptr_t secret_len,
                           uint8_t *out_sk,
                           uintptr_t out_sk_len,
                           uint8_t *out_pk,
                           uintptr_t out_pk_len);

/**
 * Hybrid encapsulation to `(pk_pq, pk_trad)`.
 *
 * Writes `out_ct_pq` ([`PQT_MLKEM768_CT_LEN`]), `out_ct_trad` ([`PQT_X25519_LEN`])
 * and `out_secret` ([`PQT_SECRET_LEN`]). `context` is bound only under
 * [`PQT_PROFILE_CONTEXT_BOUND`] and must then be non-empty.
 *
 * # Safety
 * Every `(ptr, len)` pair must describe a valid region; output buffers must be
 * writable for their lengths.
 */
int32_t pqt_hybrid_encapsulate(uint8_t profile,
                               const uint8_t *suite_id,
                               uintptr_t suite_id_len,
                               uint32_t policy_version,
                               const uint8_t *pk_pq,
                               uintptr_t pk_pq_len,
                               const uint8_t *pk_trad,
                               uintptr_t pk_trad_len,
                               const uint8_t *context,
                               uintptr_t context_len,
                               const uint8_t *rand_pq,
                               uintptr_t rand_pq_len,
                               const uint8_t *rand_trad,
                               uintptr_t rand_trad_len,
                               uint8_t *out_ct_pq,
                               uintptr_t out_ct_pq_len,
                               uint8_t *out_ct_trad,
                               uintptr_t out_ct_trad_len,
                               uint8_t *out_secret,
                               uintptr_t out_secret_len);

/**
 * Hybrid decapsulation. Returns [`PQT_OK`] and writes `out_secret`
 * ([`PQT_SECRET_LEN`]) for any correctly-sized ciphertext; an invalid ciphertext
 * yields a pseudorandom secret (implicit rejection — no oracle).
 *
 * # Safety
 * Every `(ptr, len)` pair must describe a valid region; `out_secret` must be
 * writable for [`PQT_SECRET_LEN`].
 */
int32_t pqt_hybrid_decapsulate(uint8_t profile,
                               const uint8_t *suite_id,
                               uintptr_t suite_id_len,
                               uint32_t policy_version,
                               const uint8_t *sk_pq,
                               uintptr_t sk_pq_len,
                               const uint8_t *ct_pq,
                               uintptr_t ct_pq_len,
                               const uint8_t *pk_pq,
                               uintptr_t pk_pq_len,
                               const uint8_t *sk_trad,
                               uintptr_t sk_trad_len,
                               const uint8_t *ct_trad,
                               uintptr_t ct_trad_len,
                               const uint8_t *pk_trad,
                               uintptr_t pk_trad_len,
                               const uint8_t *context,
                               uintptr_t context_len,
                               uint8_t *out_secret,
                               uintptr_t out_secret_len);

#endif  /* PQT_H */
